#!/bin/bash
#
# Download Ninja (https://ninja-build.org) and unpack it into a specific
# directory. Usage:
#
#     get-ninja v1.7.1 ~/bin
#     export PATH=~/bin:$PATH

set -e
VERSION=$1
DIRECTORY=$2

if [ "$CI_OS_NAME" == "linux" ]; then
  ZIPNAME=ninja-linux.zip
elif [ "$CI_OS_NAME" == "osx" ]; then
  ZIPNAME=ninja-mac.zip
elif [ "$CI_OS_NAME" == "windows" ]; then
  ZIPNAME=ninja-win.zip
else
  echo "error: \$CI_OS_NAME=\"$CI_OS_NAME\" is not supported"
  exit 1
fi
TEMPFILE=$(mktemp)_$ZIPNAME
URL=https://github.com/ninja-build/ninja/releases/download/$VERSION/$ZIPNAME

set -e
mkdir -p "$DIRECTORY"
echo "Downloading \"$URL\" ..."
curl -sSfLo $TEMPFILE $URL
unzip -qod $DIRECTORY $TEMPFILE
rm $TEMPFILE
echo "installed Ninja-$VERSION to \"$DIRECTORY\""
